name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily
  workflow_dispatch: # Allows manual run

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg  # <-- Fix output path

      - name: Push to output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b output
          git add snake.svg
          git commit -m "Generated snake.svg"
          git push origin output --force
